-- Add sample learning resources with URLs for webview testing
INSERT INTO learning_resources (title, content, category, difficulty_level, estimated_read_time, xp_reward, tags, author_name, author_title, url, is_featured) VALUES
('The Science of Modern Dating: A Comprehensive Guide', 'This comprehensive guide explores the psychology and science behind modern dating apps and online relationships. Learn about algorithms, matching patterns, and how to optimize your dating profile for success.', 'profile', 2, 15, 30, ARRAY['dating', 'psychology', 'apps'], 'Dr. Emily Rodriguez', 'Behavioral Psychologist', 'https://www.psychologytoday.com/us/blog/the-attraction-doctor/202301/the-science-online-dating', true),

('Mastering First Impressions in Digital Dating', 'Discover the key elements that make a lasting first impression in online dating. From profile photos to opening messages, learn the strategies that lead to meaningful connections.', 'messaging', 1, 8, 20, ARRAY['first-impressions', 'profile', 'messages'], 'Sarah Chen', 'Dating Coach & Author', 'https://www.thesocialman.com/first-impressions-online-dating/', false),

('Red Flags and Green Lights: Navigating Online Dating Safety', 'Essential guide to identifying potential red flags while recognizing positive signals in online dating. Learn how to protect yourself while staying open to genuine connections.', 'social', 3, 12, 25, ARRAY['safety', 'red-flags', 'awareness'], 'Michael Thompson', 'Relationship Safety Expert', 'https://www.safety.com/dating/online-dating-red-flags/', true),

('Building Emotional Intelligence for Better Relationships', 'Develop the emotional awareness and communication skills that create deeper, more meaningful relationships. Learn to understand yourself and your partner better.', 'relationship', 3, 20, 35, ARRAY['emotional-intelligence', 'communication', 'relationships'], 'Dr. Amanda Foster', 'Clinical Psychologist', 'https://www.verywellmind.com/what-is-emotional-intelligence-2795423', false),

('The Art of Conversation: From Small Talk to Deep Connections', 'Transform your conversational skills with proven techniques for engaging dialogue. Learn how to move beyond surface-level chat to create genuine connections.', 'messaging', 2, 10, 25, ARRAY['conversation', 'communication', 'connection'], 'James Wilson', 'Social Skills Coach', 'https://www.themuse.com/advice/how-to-have-a-good-conversation', true);